using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class stdBall : MonoBehaviour
{
    public bool isAutoInit = true;
    public int countSpeedUp = 0;
    public float att = 1.1f;
    public double BallLevel = 1;
    private const int MIN = 8, MAX = 16;
    private const string BALL_TAG = "Ball", WALL_TAG = "Wall";
    private Rigidbody rb;

    public void InitSpeed(int min, int max) // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½minï¿½ï¿½ï¿½ï¿½max
    {
        // Random.Rangeï¿½ÍAï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ <= return < ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Å‚ï¿½ï¿½ï¿½
        rb.velocity += Vector3.right * Random.Range(min, max + 1);
        rb.velocity += Vector3.forward * Random.Range(min, max + 1);

        // ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½+-ï¿½ï¿½ï¿½tï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (System.Convert.ToBoolean(Random.Range(0, 2)))
            rb.velocity = new Vector3(-1 * rb.velocity.x, rb.velocity.y, rb.velocity.z);
        if (System.Convert.ToBoolean(Random.Range(0, 2)))
            rb.velocity = new Vector3(rb.velocity.x, rb.velocity.y, -1 * rb.velocity.z);

        // ForceMode.VelocityChangeï¿½F
        // ï¿½ï¿½ï¿½Ê‚ğ–³ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½1ï¿½bï¿½Ô—Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½lvelocityï¿½ï¿½Ï‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È—ï¿½ï¿½ï¿½ï¿½ï¿½ÆA0.02ï¿½b(1ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½)ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        //if (System.Convert.ToBoolean(Random.Range(0, 2)))
        //    rb.AddForce(new Vector3(rb.velocity.x * -2, 0, 0), ForceMode.VelocityChange);
        //if (System.Convert.ToBoolean(Random.Range(0, 2)))
        //    rb.AddForce(new Vector3(0, 0, rb.velocity.z * -2), ForceMode.VelocityChange);
    }
    void Start()
    {
        rb = GetComponent<Rigidbody>();
        countSpeedUp = 0;

        if (isAutoInit)
        {
            InitSpeed(MIN, MAX);
        }
    }

    void Update()
    {
        // test
        if (Input.GetKeyDown(KeyCode.Space))
        {
            rotate(1);
        }
    }

    // ï¿½Nï¿½ï¿½ï¿½Xï¿½Ìƒï¿½ï¿½ï¿½ï¿½oï¿½Ïï¿½ï¿½ğ’¼Ú‚ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚Í‚ï¿½ë‚µï¿½ï¿½ï¿½È‚ï¿½ï¿½ç‚µï¿½ï¿½ï¿½Ì‚Å—pï¿½Ó‚ï¿½ï¿½ï¿½
    // ï¿½dï¿½ï¿½ï¿½È‚ï¿½æ‚¤ï¿½È‚ç’¼ï¿½Úï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½æ‚¤
    public Vector3 getVelocity()
    {
        return rb.velocity;
    }


    public void changeVelocity(Vector3 velocity)
    {
        rb.velocity = velocity;
    }


    public void addVelocity(float x, float y, float z)
    {
        rb.velocity = new Vector3(rb.velocity.x + x, rb.velocity.y + y, rb.velocity.z + z);
    }

    public void addVelocity(Vector3 vec)
    {
        rb.velocity += vec;
    }


    public void multiplyVelocity(float num)
    {
        rb.velocity *= num;
    }

    public void multiplyVelocity(float x, float y, float z)
    {
        rb.velocity = new Vector3(rb.velocity.x * x, rb.velocity.y * y, rb.velocity.z * z);
    }

    public void multiplyVelocity(Vector3 vec)
    {
        float x = vec.x;
        float y = vec.y;
        float z = vec.z;
        rb.velocity = new Vector3(rb.velocity.x * x, rb.velocity.y * y, rb.velocity.z * z);
    }

    // numï¿½ï¿½90ï¿½xï¿½ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½@ï¿½}ï¿½Cï¿½iï¿½Xï¿½ï¿½ï¿½ï¿½
    public void rotate(int num)
    {
        // ï¿½á‚¦ï¿½ï¿½ -7%4 ï¿½ï¿½ -3 ï¿½Æ‚È‚ï¿½Ì‚ÅAï¿½Ü‚ï¿½ï¿½vï¿½ï¿½ï¿½Xï¿½É‚ï¿½ï¿½ï¿½
        while (num < 0)
            num += 4;
        num %= 4;
        // 90ï¿½xï¿½ï¿½]
        for (int i = 0; i < num; i++)
            rb.velocity = new Vector3(rb.velocity.z, rb.velocity.y, -rb.velocity.x);
    }

    public void OnRefrection(string obj) // ï¿½ï¿½ï¿½ÅŒï¿½ï¿½ß‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½uï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½oï¿½[ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½è‚·ï¿½ï¿½
    {
        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½éˆï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ç‘ï¿½ï¿½
    }

    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.tag == WALL_TAG)
        {
            //Debug.Log("ï¿½Ô‚Â‚ï¿½ï¿½ï¿½ï¿½ï¿½");

            //// BALL_TAGï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½Ì‘Sï¿½Ä‚ï¿½zï¿½ï¿½É“ï¿½ï¿½ï¿½ï¿½
            //GameObject[] balls = GameObject.FindGameObjectsWithTag(BALL_TAG);

            //Debug.Log(balls.Length);

            //for (int i = 0; i < balls.Length; i++)
            //{
            //}

            //// ï¿½zï¿½ï¿½Ìˆï¿½Âˆï¿½Â‚ï¿½ballï¿½É“ï¿½ï¿½ï¿½
            //foreach (GameObject ball in balls)
            //{
            //    stdBall stdBall = ball.gameObject.GetComponent<stdBall>();
            //    stdBall.count++;
            //}
        }
    }
    private void OnCollisionStay(Collision collision)
    {
        if (collision.gameObject.tag == WALL_TAG)
        {
            //Debug.Log("ï¿½Ô‚Â‚ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½");
        }
    }
    private void OnCollisionExit(Collision collision)
    {
        if (collision.gameObject.tag == WALL_TAG)
        {
            //Debug.Log("ï¿½ï¿½ï¿½ê‚½");
        }
    }
}
